name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop

jobs:
  run-cli:
    runs-on: ubuntu-latest
    steps:
    - uses: action/cehckout@v2
    - uses: action/setup-go@v2
      with:
        go-version: 1.15
    - run: go test -coverprofile=coverage.out